apiVersion: v1
kind: Service
metadata:
  labels:
    app: overview-broker
  name: overview-broker
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: overview-broker
