apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: brokeredserviceinstances.ism.ism.pivotal.io
spec:
  group: ism.ism.pivotal.io
  names:
    kind: BrokeredServiceInstance
    plural: brokeredserviceinstances
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            guid:
              type: string
            migrated:
              type: boolean
            name:
              type: string
            planId:
              type: string
            serviceId:
              type: string
          type: object
        status:
          properties:
            async:
              type: boolean
            success:
              type: boolean
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
