apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: brokeredservicebindings.ism.ism.pivotal.io
spec:
  group: ism.ism.pivotal.io
  names:
    kind: BrokeredServiceBinding
    plural: brokeredservicebindings
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            platformAttachmentContext:
              type: string
            platformName:
              type: string
            serviceInstanceName:
              type: string
          type: object
        status:
          properties:
            success:
              type: boolean
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
