apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: brokeredserviceinstances.ism.ism.pivotal.io
spec:
  group: ism.ism.pivotal.io
  names:
    kind: BrokeredServiceInstance
    plural: brokeredserviceinstances
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            name:
              type: string
            plan:
              type: string
            service:
              type: string
          type: object
        status:
          properties:
            response:
              properties:
                async:
                  type: boolean
              type: object
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
