---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ismteam/ci
    tag: 0.0.2

inputs:
- name: ism
  path: src/github.com/pivotal-cf/ism

params:
- KUBECONFIG_FILE_CONTENTS:
- TEST_ACCEPTANCE_IN_CLUSTER: true

run:
  path: src/github.com/pivotal-cf/ism/ci/shim
  args:
     - make
     - acceptance-tests
