---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: teddyking/ism-ci
    tag: 0.0.1

inputs:
- name: ism
  path: src/github.com/pivotal-cf/ism

run:
  path: src/github.com/pivotal-cf/ism/ci/shim
  args:
    - make
    - test
