---
jobs:
- name: absolute-unit
  plan:
  - get: ism
    trigger: true
  - task: unit
    file: ism/ci/tasks/unit.yml

- name: integration
  plan:
  - get: ism
    trigger: true
  - task: integration
    file: ism/ci/tasks/integration.yml

- name: build-controller-image
  plan:
  - get: ism
    trigger: true
    passed: [absolute-unit, integration]
  - put: ism-controller-image
    params: {build: ism}

- name: acceptance
  plan:
  - get: ism
    trigger: true
    passed: [build-controller-image]
  - task: acceptance
    file: ism/ci/tasks/acceptance.yml
    params:
      KUBECONFIG_FILE_CONTENTS: {{KUBECONFIG_FILE_CONTENTS}}

resources:
- name: ism
  type: git
  source:
    uri: https://github.com/pivotal-cf/ism
    branch: master

- name: ism-controller-image
  type: docker-image
  source:
    repository: ismteam/controller
    username: {{DOCKERHUB_USERNAME}}
    password: {{DOCKERHUB_PASSWORD}}
