---
jobs:
- name: absolute-unit
  plan:
  - get: ism
    trigger: true
  - task: unit
    file: ism/ci/tasks/unit.yml

- name: integration
  plan:
  - get: ism
    trigger: true
  - task: integration
    file: ism/ci/tasks/integration.yml

- name: acceptance
  plan:
  - get: ism
    trigger: true
  - task: acceptance
    file: ism/ci/tasks/acceptance.yml
    params:
      KUBECONFIG_FILE_CONTENTS: {{KUBECONFIG_FILE_CONTENTS}}
      BROKER_URL: {{BROKER_URL}}
      BROKER_USERNAME: {{BROKER_USERNAME}}
      BROKER_PASSWORD: {{BROKER_PASSWORD}}


resources:
- name: ism
  type: git
  source:
    uri: https://github.com/pivotal-cf/ism
    branch: master
